---
name: Docker build image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main  # Trigger CI on main branch
    paths:
      - 'GameCode/**'
      - Dockerfile
      - nginx.conf
      - '.forgejo/workflows/dockerBuild.yml'
  pull_request:
    branches:
      - main  # Trigger gated pipeline on PR to main
    paths:
      - 'GameCode/**'
      - Dockerfile
      - nginx.conf
      - '.forgejo/workflows/dockerBuild.yml'

env:
  REGISTRY: forgejo.themongoose.xyz/brandon/
  IMAGE_NAME: godot_tutorial

jobs:
  build-and-push-image:
    runs-on: docker
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: https://forgejo.themongoose.xyz/actions/checkout@v4
      - run: git lfs pull
      - name: Log in to the forgejo Container registry
        uses: https://forgejo.themongoose.xyz/actions/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.FORGEJO_DOCKER_USER }}
          password: ${{ secrets.FORGEJO_DOCKER_TOKEN }}
      - name: Build Docker image (non main branch)
        uses: https://forgejo.themongoose.xyz/actions/build-push-action@090ca155fc9b214cbcac536c450455a0e96f52c6
        if: github.ref != 'refs/heads/main'
        with:
          context: .
          load: false
          push: true
          tags: |
            ${{ env.REGISTRY }}${{ env.IMAGE_NAME }}:ci
      - name: Build Docker image (main branch)
        uses: https://forgejo.themongoose.xyz/actions/build-push-action@090ca155fc9b214cbcac536c450455a0e96f52c6
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          load: false
          push: true
          tags: |
            ${{ env.REGISTRY }}${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}${{ env.IMAGE_NAME }}:main
